delete
from users;

delete
from categories;

alter table users
    alter column user_id restart with 1;

alter table categories
    alter column category_id restart with 1;


create table if not exists users
(
    user_id    integer generated by default as identity
        constraint users_pk
            primary key,
    user_email varchar(50)  not null
        constraint users_pk_2
            unique,
    user_name  varchar(250) not null
);

alter table users
    owner to ewm;

create table if not exists categories
(
    category_id   integer generated by default as identity
        constraint categories_pk
            primary key,
    category_name varchar(50) not null
        constraint categories_name_key
            unique
);

alter table categories
    owner to ewm;